#!/usr/bin/python
import codecs
import os
import sys
import tempfile

# Usage:
# ./pmv <files to rename>
# e.g. ./pmv 1020102.pdf 23510924.pdf fast_paper_10.pdf
#
# By default, files land in your current directory.  To specify an output 
# directory, use the format:
# ./pmv --dir my/output/directory <files> 
#
# or simply modify this file.

renamepath = '~/code/scripts/pdf_namer/' # Input the path to rename_by_title.py.  It is pure laziness
                # that prevents this from being packaged.

while renamepath == '':
  renamepath = raw_input('Please enter the path to rename_by_title.py')

sys.path.append(renamepath)           

from rename_by_title import *
if sys.argv[1] == '--dir':
  paper_dir = sys.argv[2]
  sys.argv.pop(1)
  sys.argv.pop(1)
else:
  paper_dir = './'
files = sys.argv[1:]
print 'Saving output to',paper_dir
for pdf_name in files:
  _, tmp_name = tempfile.mkstemp()
  try:
    with open(pdf_name, 'r') as pdf_file, open(tmp_name, 'w') as tmp_file:
      parse_first_page(pdf_file, tmp_file)
    print 'Successfully parsed', pdf_name
    with codecs.open(tmp_name,'r','utf-8') as pdf_text:
      title = guess_title(pdf_text)
    fn = title_rename(title, pdf_name)
    os.rename(fn, paper_dir + fn)
  finally:
    os.remove(tmp_name)
